# See https://pre-commit.com for more hooks
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.9
    hooks:
      - id: ruff
        args:
          - --fix
      - id: ruff-format

  - repo: local
    hooks:
      - id: pyrefly
        name: Pyrefly (type checking)
        entry: bash -c 'uv run pyrefly check'
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
