# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: src/shared/event_bus/proto/domain_event.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, '', 'src/shared/event_bus/proto/domain_event.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n-src/shared/event_bus/proto/domain_event.proto\x12\x10ticketing.events"\xf4\x01\n\x0b\x44omainEvent\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x12\n\nevent_type\x18\x02 \x01(\t\x12\x14\n\x0c\x61ggregate_id\x18\x03 \x01(\t\x12\x16\n\x0e\x61ggregate_type\x18\x04 \x01(\t\x12\x13\n\x0boccurred_at\x18\x05 \x01(\x03\x12=\n\x08metadata\x18\x06 \x03(\x0b\x32+.ticketing.events.DomainEvent.MetadataEntry\x12\x0c\n\x04\x64\x61ta\x18\x07 \x01(\x0c\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01"\x89\x01\n\x14TicketsReservedEvent\x12\x10\n\x08\x62uyer_id\x18\x01 \x01(\t\x12\x12\n\nbooking_id\x18\x02 \x01(\t\x12\x12\n\nticket_ids\x18\x03 \x03(\t\x12\x10\n\x08\x65vent_id\x18\x04 \x01(\t\x12\x10\n\x08quantity\x18\x05 \x01(\x05\x12\x13\n\x0btotal_price\x18\x06 \x01(\x01"\x9d\x01\n\x1cTicketReservationFailedEvent\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x10\n\x08\x62uyer_id\x18\x02 \x01(\t\x12\x10\n\x08\x65vent_id\x18\x03 \x01(\t\x12\x12\n\nerror_code\x18\x04 \x01(\t\x12\x15\n\rerror_message\x18\x05 \x01(\t\x12\x1a\n\x12requested_quantity\x18\x06 \x01(\x05"\x7f\n\x10\x42ookingPaidEvent\x12\x12\n\nbooking_id\x18\x01 \x01(\t\x12\x10\n\x08\x62uyer_id\x18\x02 \x01(\t\x12\x12\n\npayment_id\x18\x03 \x01(\t\x12\x0e\n\x06\x61mount\x18\x04 \x01(\x01\x12\x10\n\x08\x63urrency\x18\x05 \x01(\t\x12\x0f\n\x07paid_at\x18\x06 \x01(\x03"\x80\x01\n\x15\x42ookingCancelledEvent\x12\x12\n\nbooking_id\x18\x01 \x01(\t\x12\x10\n\x08\x62uyer_id\x18\x02 \x01(\t\x12\x0e\n\x06reason\x18\x03 \x01(\t\x12\x14\n\x0c\x63\x61ncelled_at\x18\x04 \x01(\x03\x12\x1b\n\x13refunded_ticket_ids\x18\x05 \x03(\tb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, 'src.shared.event_bus.proto.domain_event_pb2', _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals['_DOMAINEVENT_METADATAENTRY']._loaded_options = None
    _globals['_DOMAINEVENT_METADATAENTRY']._serialized_options = b'8\001'
    _globals['_DOMAINEVENT']._serialized_start = 68
    _globals['_DOMAINEVENT']._serialized_end = 312
    _globals['_DOMAINEVENT_METADATAENTRY']._serialized_start = 265
    _globals['_DOMAINEVENT_METADATAENTRY']._serialized_end = 312
    _globals['_TICKETSRESERVEDEVENT']._serialized_start = 315
    _globals['_TICKETSRESERVEDEVENT']._serialized_end = 452
    _globals['_TICKETRESERVATIONFAILEDEVENT']._serialized_start = 455
    _globals['_TICKETRESERVATIONFAILEDEVENT']._serialized_end = 612
    _globals['_BOOKINGPAIDEVENT']._serialized_start = 614
    _globals['_BOOKINGPAIDEVENT']._serialized_end = 741
    _globals['_BOOKINGCANCELLEDEVENT']._serialized_start = 744
    _globals['_BOOKINGCANCELLEDEVENT']._serialized_end = 872
# @@protoc_insertion_point(module_scope)
