# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: domain_event.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, '', 'domain_event.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x12\x64omain_event.proto\x12\x10ticketing.events"\xa3\x02\n\x19\x42ookingCreatedDomainEvent\x12\x12\n\nbooking_id\x18\x01 \x01(\t\x12\x10\n\x08\x62uyer_id\x18\x02 \x01(\x05\x12\x10\n\x08\x65vent_id\x18\x03 \x01(\x05\x12\x13\n\x0btotal_price\x18\x04 \x01(\x05\x12\x0f\n\x07section\x18\x05 \x01(\t\x12\x12\n\nsubsection\x18\x06 \x01(\x05\x12\x10\n\x08quantity\x18\x07 \x01(\x05\x12\x1b\n\x13seat_selection_mode\x18\x08 \x01(\t\x12\x16\n\x0eseat_positions\x18\t \x03(\t\x12\x0e\n\x06status\x18\n \x01(\t\x12\x13\n\x0btraceparent\x18\x0c \x01(\t\x12\x12\n\ntracestate\x18\r \x01(\t\x12\x14\n\x0cmessage_type\x18\x0e \x01(\t"\xa1\x01\n\x15\x42ookingCancelledEvent\x12\x12\n\nbooking_id\x18\x01 \x01(\t\x12\x10\n\x08\x65vent_id\x18\x02 \x01(\x05\x12\x0f\n\x07section\x18\x03 \x01(\t\x12\x12\n\nsubsection\x18\x04 \x01(\x05\x12\x13\n\x0btraceparent\x18\x05 \x01(\t\x12\x12\n\ntracestate\x18\x06 \x01(\t\x12\x14\n\x0cmessage_type\x18\x07 \x01(\tb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'domain_event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals['_BOOKINGCREATEDDOMAINEVENT']._serialized_start = 41
    _globals['_BOOKINGCREATEDDOMAINEVENT']._serialized_end = 332
    _globals['_BOOKINGCANCELLEDEVENT']._serialized_start = 335
    _globals['_BOOKINGCANCELLEDEVENT']._serialized_end = 496
# @@protoc_insertion_point(module_scope)
