# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: src/platform/message_queue/proto/domain_event.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import (
    descriptor as _descriptor,
    descriptor_pool as _descriptor_pool,
    runtime_version as _runtime_version,
    symbol_database as _symbol_database,
)
from google.protobuf.internal import builder as _builder


_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'src/platform/message_queue/proto/domain_event.proto',
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n1src/platform/message_queue/proto/domain_event.proto\x12\x10ticketing.events"\xf8\x01\n\rMqDomainEvent\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x12\n\nevent_type\x18\x02 \x01(\t\x12\x14\n\x0c\x61ggregate_id\x18\x03 \x01(\t\x12\x16\n\x0e\x61ggregate_type\x18\x04 \x01(\t\x12\x13\n\x0boccurred_at\x18\x05 \x01(\x03\x12?\n\x08metadata\x18\x06 \x03(\x0b\x32-.ticketing.events.MqDomainEvent.MetadataEntry\x12\x0c\n\x04\x64\x61ta\x18\x07 \x01(\x0c\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01"\x89\x01\n\x14TicketsReservedEvent\x12\x10\n\x08\x62uyer_id\x18\x01 \x01(\t\x12\x12\n\nbooking_id\x18\x02 \x01(\t\x12\x12\n\nticket_ids\x18\x03 \x03(\t\x12\x10\n\x08\x65vent_id\x18\x04 \x01(\t\x12\x10\n\x08quantity\x18\x05 \x01(\x05\x12\x13\n\x0btotal_price\x18\x06 \x01(\x01"\x9d\x01\n\x1cTicketReservationFailedEvent\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x10\n\x08\x62uyer_id\x18\x02 \x01(\t\x12\x10\n\x08\x65vent_id\x18\x03 \x01(\t\x12\x12\n\nerror_code\x18\x04 \x01(\t\x12\x15\n\rerror_message\x18\x05 \x01(\t\x12\x1a\n\x12requested_quantity\x18\x06 \x01(\x05"\x7f\n\x10\x42ookingPaidEvent\x12\x12\n\nbooking_id\x18\x01 \x01(\t\x12\x10\n\x08\x62uyer_id\x18\x02 \x01(\t\x12\x12\n\npayment_id\x18\x03 \x01(\t\x12\x0e\n\x06\x61mount\x18\x04 \x01(\x01\x12\x10\n\x08\x63urrency\x18\x05 \x01(\t\x12\x0f\n\x07paid_at\x18\x06 \x01(\x03"\x80\x01\n\x15\x42ookingCancelledEvent\x12\x12\n\nbooking_id\x18\x01 \x01(\t\x12\x10\n\x08\x62uyer_id\x18\x02 \x01(\t\x12\x0e\n\x06reason\x18\x03 \x01(\t\x12\x14\n\x0c\x63\x61ncelled_at\x18\x04 \x01(\x03\x12\x1b\n\x13refunded_ticket_ids\x18\x05 \x03(\tb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, 'src.platform.message_queue.proto.domain_event_pb2', _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals['_MQDOMAINEVENT_METADATAENTRY']._loaded_options = None
    _globals['_MQDOMAINEVENT_METADATAENTRY']._serialized_options = b'8\001'
    _globals['_MQDOMAINEVENT']._serialized_start = 72
    _globals['_MQDOMAINEVENT']._serialized_end = 320
    _globals['_MQDOMAINEVENT_METADATAENTRY']._serialized_start = 273
    _globals['_MQDOMAINEVENT_METADATAENTRY']._serialized_end = 320
    _globals['_TICKETSRESERVEDEVENT']._serialized_start = 323
    _globals['_TICKETSRESERVEDEVENT']._serialized_end = 460
    _globals['_TICKETRESERVATIONFAILEDEVENT']._serialized_start = 463
    _globals['_TICKETRESERVATIONFAILEDEVENT']._serialized_end = 620
    _globals['_BOOKINGPAIDEVENT']._serialized_start = 622
    _globals['_BOOKINGPAIDEVENT']._serialized_end = 749
    _globals['_BOOKINGCANCELLEDEVENT']._serialized_start = 752
    _globals['_BOOKINGCANCELLEDEVENT']._serialized_end = 880
# @@protoc_insertion_point(module_scope)
