"""booking new colfasalifijfaumn

Revision ID: 01de4686c3d7
Revises: c2f7e34fa7f6
Create Date: 2025-09-24 21:24:06.027009

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01de4686c3d7'
down_revision: Union[str, Sequence[str], None] = 'c2f7e34fa7f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'booking_ticket',
        sa.Column('booking_id', sa.Integer(), nullable=False),
        sa.Column('ticket_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['booking_id'],
            ['booking.id'],
        ),
        sa.ForeignKeyConstraint(
            ['ticket_id'],
            ['ticket.id'],
        ),
        sa.PrimaryKeyConstraint('booking_id', 'ticket_id'),
    )
    op.add_column('booking', sa.Column('seat_positions', sa.ARRAY(sa.Integer()), nullable=True))
    op.drop_column('booking', 'ow_number')
    op.drop_column('booking', 'seat_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'booking', sa.Column('seat_number', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.add_column(
        'booking', sa.Column('ow_number', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.drop_column('booking', 'seat_positions')
    op.drop_table('booking_ticket')
    # ### end Alembic commands ###
