"""add venue_name and seating_config to event

Revision ID: 41849eb09de2
Revises: 8917ff70228d
Create Date: 2025-09-13 15:22:08.209910

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41849eb09de2'
down_revision: Union[str, Sequence[str], None] = '8917ff70228d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('venue_name', sa.String(length=255), nullable=False))
    op.add_column('event', sa.Column('seating_config', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'seating_config')
    op.drop_column('event', 'venue_name')
    # ### end Alembic commands ###
