"""recreate ticket table

Revision ID: 47b017b88247
Revises: b5d48fa4c987
Create Date: 2025-09-14 20:12:07.894703

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47b017b88247'
down_revision: Union[str, Sequence[str], None] = 'b5d48fa4c987'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Recreate ticket table that was accidentally dropped
    op.create_table(
        'ticket',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('event_id', sa.Integer(), nullable=False),
        sa.Column('section', sa.String(length=10), nullable=False),
        sa.Column('subsection', sa.Integer(), nullable=False),
        sa.Column('row_number', sa.Integer(), nullable=False),
        sa.Column('seat_number', sa.Integer(), nullable=False),
        sa.Column('price', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(length=20), server_default='available', nullable=False),
        sa.Column('order_id', sa.Integer(), nullable=True),
        sa.Column('buyer_id', sa.Integer(), nullable=True),
        sa.Column('reserved_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['buyer_id'],
            ['user.id'],
        ),
        sa.ForeignKeyConstraint(
            ['event_id'],
            ['event.id'],
        ),
        sa.ForeignKeyConstraint(
            ['order_id'],
            ['order.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'event_id', 'section', 'subsection', 'row_number', 'seat_number', name='uq_ticket_seat'
        ),
    )
    op.create_index(op.f('idx_ticket_buyer_id'), 'ticket', ['buyer_id'], unique=False)
    op.create_index(op.f('idx_ticket_event_id'), 'ticket', ['event_id'], unique=False)
    op.create_index(
        op.f('idx_ticket_event_section'),
        'ticket',
        ['event_id', 'section', 'subsection'],
        unique=False,
    )
    op.create_index(op.f('idx_ticket_order_id'), 'ticket', ['order_id'], unique=False)
    op.create_index(
        op.f('idx_ticket_seat_lookup'),
        'ticket',
        ['event_id', 'section', 'subsection', 'row_number', 'seat_number'],
        unique=False,
    )
    op.create_index(op.f('idx_ticket_status'), 'ticket', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_ticket_status'), table_name='ticket')
    op.drop_index(op.f('idx_ticket_seat_lookup'), table_name='ticket')
    op.drop_index(op.f('idx_ticket_order_id'), table_name='ticket')
    op.drop_index(op.f('idx_ticket_event_section'), table_name='ticket')
    op.drop_index(op.f('idx_ticket_event_id'), table_name='ticket')
    op.drop_index(op.f('idx_ticket_buyer_id'), table_name='ticket')
    op.drop_table('ticket')
    # ### end Alembic commands ###
