"""booking

Revision ID: 9f58c0178695
Revises: e81ceb1a3ad6
Create Date: 2025-09-25 01:17:58.835359

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f58c0178695'
down_revision: Union[str, Sequence[str], None] = 'e81ceb1a3ad6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'booking',
        'subsection',
        existing_type=sa.VARCHAR(length=10),
        type_=sa.Integer(),
        existing_nullable=False,
        postgresql_using='subsection::integer',
    )
    op.alter_column(
        'booking',
        'seat_positions',
        existing_type=postgresql.ARRAY(sa.INTEGER()),
        type_=sa.ARRAY(sa.String()),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'booking',
        'seat_positions',
        existing_type=sa.ARRAY(sa.String()),
        type_=postgresql.ARRAY(sa.INTEGER()),
        existing_nullable=True,
    )
    op.alter_column(
        'booking',
        'subsection',
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(length=10),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
