"""booking new column

Revision ID: c2f7e34fa7f6
Revises: 08b5c635cb21
Create Date: 2025-09-24 21:13:52.273114

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = 'c2f7e34fa7f6'
down_revision: Union[str, Sequence[str], None] = '08b5c635cb21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
