"""squash all booking migrations

Revision ID: e81ceb1a3ad6
Revises: 01de4686c3d7
Create Date: 2025-09-24 21:29:14.229606

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = 'e81ceb1a3ad6'
down_revision: Union[str, Sequence[str], None] = '01de4686c3d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
